extends SceneTree

class MyObject:
	@export
	var test : int = 5
	@export
	var pos : Vector3 = Vector3(1, 2, 3)
	@export
	var color : Color = Color.RED
	@export
	var data : PackedByteArray = [1, 2, 3]
	@export
	var names : PackedStringArray = ["one", "two"]

	var sub : MySubObject = MySubObject.new()

class MySubObject:
	@export
	var id : String = "sub_id"
	@export
	var value : float = 1.0

var scalar_types:Dictionary = {
	TYPE_INT: "int",
	TYPE_FLOAT: "float",
	TYPE_BOOL: "bool",
	TYPE_STRING: "string",
}

var struct_types:Dictionary = {
	TYPE_VECTOR2: "Vector2",
	TYPE_VECTOR2I: "Vector2i",
	TYPE_RECT2: "Rect2",
	TYPE_RECT2I: "Rect2i",
	TYPE_VECTOR3: "Vector3",
	TYPE_VECTOR3I: "Vector3i",
	TYPE_VECTOR4: "Vector4",
	TYPE_VECTOR4I: "Vector4i",
	TYPE_PLANE: "Plane",
	TYPE_QUATERNION: "Quaternion",
	TYPE_AABB: "AABB",
	TYPE_BASIS: "Basis",
	TYPE_TRANSFORM2D: "Transform2D",
	TYPE_TRANSFORM3D: "Transform3D",
	TYPE_PROJECTION: "Projection",
	TYPE_COLOR: "Color",
}

var packed_array_types:Dictionary = {
	TYPE_PACKED_BYTE_ARRAY: "ubyte",
	TYPE_PACKED_INT32_ARRAY: "int",
	TYPE_PACKED_INT64_ARRAY: "long",
	TYPE_PACKED_FLOAT32_ARRAY: "float",
	TYPE_PACKED_FLOAT64_ARRAY: "double",
	TYPE_PACKED_STRING_ARRAY: "string",
	TYPE_PACKED_VECTOR2_ARRAY: "Vector2",
	TYPE_PACKED_VECTOR3_ARRAY: "Vector3",
	TYPE_PACKED_COLOR_ARRAY: "Color",
	TYPE_PACKED_VECTOR4_ARRAY: "Vector4",
}

func _init() -> void:
	var object := MyObject.new()

	var chunks : Array[String] = []
	var object_table:String = generate_table( "MyObject", object, chunks )
	chunks.append(object_table)
	var schema = generate_schema("MyObject", chunks)

	print("--- SCHEMA START ---")
	print(schema)
	print("--- SCHEMA END ---")

	var file = FileAccess.open("C:/Godot/Projects/HelloWorld/addons/enetheru.flatbuffers-addon/res/generated_test.fbs", FileAccess.WRITE)
	if file:
		file.store_string(schema)
		file.close()
		print("Saved to C:/Godot/Projects/HelloWorld/addons/enetheru.flatbuffers-addon/res/generated_test.fbs")
	else:
		print("Failed to open file for writing: ", FileAccess.get_open_error())

	quit()

func export_filter( prop_info : Dictionary ) -> bool:
	if not (prop_info.usage & PROPERTY_USAGE_STORAGE):
		return false

	if prop_info.type in scalar_types: return true
	if prop_info.type in struct_types: return true
	if prop_info.type in packed_array_types: return true
	if prop_info.type == TYPE_OBJECT: return true
	if prop_info.type == TYPE_ARRAY: return true

	return false

func generate_schema( root : String, chunks : Array[String] ) -> String:
	var lines:Array[String] = ["// Generated By gdflatbuffers", "include \"godot.fbs\";", ""]
	for chunk : String in chunks:
		lines.append(chunk)
	lines.append_array(["", "root_type {root};".format({"root": root})])
	return "\n".join( lines )

func generate_table( type_name : String, object:Object, chunks : Array[String], generated_tables : Array[String] = [] ) -> String:
	if type_name in generated_tables:
		return ""
	generated_tables.append(type_name)

	var lines : Array[String] = [""]
	var export_list : Array[Dictionary] = object.get_property_list().filter(export_filter)

	lines.append("table {type} {".format( {"type":type_name} ) )

	for prop_info in export_list:
		var fb_type : String = ""
		if prop_info.type in scalar_types:
			fb_type = scalar_types[prop_info.type]
		elif prop_info.type in struct_types:
			fb_type = struct_types[prop_info.type]
		elif prop_info.type in packed_array_types:
			fb_type = "[%s]" % packed_array_types[prop_info.type]
		elif prop_info.type == TYPE_ARRAY:
			fb_type = "[string]"
		elif prop_info.type == TYPE_OBJECT:
			var sub_obj = object.get(prop_info.name)
			if sub_obj:
				var sub_type = sub_obj.get_class()
				if sub_obj.get_script():
					sub_type = sub_obj.get_script().get_global_name()
					if sub_type == "":
						sub_type = prop_info.name.capitalize().replace(" ", "")
				fb_type = sub_type
				var sub_table = generate_table(sub_type, sub_obj, chunks, generated_tables)
				if sub_table != "":
					chunks.append(sub_table)
			else:
				fb_type = "string"

		if fb_type != "":
			var field : String = "  {name}: {type};".format( {"name": prop_info.name, "type": fb_type} )
			lines.append( field )

	lines.append("}")
	return "\n".join(lines)
